package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-18T21:34:03.385+02:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://web/", name = "OnlineIntegration")
@XmlSeeAlso({ObjectFactory.class})
public interface OnlineIntegration {

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://web/", className = "web.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://web/", className = "web.LoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public web.SessionResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod
    @RequestWrapper(localName = "register", targetNamespace = "http://web/", className = "web.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://web/", className = "web.RegisterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public web.SessionResponse register(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebMethod
    @RequestWrapper(localName = "init", targetNamespace = "http://web/", className = "web.Init")
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://web/", className = "web.InitResponse")
    public void init();
}
