package com.Wsdl2Code.WebServices.OnlineIntegrationService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.6
//
// Date Of Creation: 5/24/2016 5:51:24 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.OnlineIntegrationService.userData;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class sessionData implements KvmSerializable {
    
    public boolean hasEnded;
    public String identifier;
    public userData user;
    
    public sessionData(){}
    
    public sessionData(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("hasEnded"))
        {
            Object obj = soapObject.getProperty("hasEnded");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                hasEnded = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                hasEnded = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("identifier"))
        {
            Object obj = soapObject.getProperty("identifier");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                identifier = j.toString();
            }else if (obj!= null && obj instanceof String){
                identifier = (String) obj;
            }
        }
        if (soapObject.hasProperty("user"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("user");
            user =  new userData (j);
            
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return hasEnded;
            case 1:
                return identifier;
            case 2:
                return user;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 3;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "hasEnded";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "identifier";
                break;
            case 2:
                info.type = userData.class;
                info.name = "user";
                break;
        }
    }
    
    @Override
    public String getInnerText() {
        return null;
    }
    
    
    @Override
    public void setInnerText(String s) {
    }
    
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
