package webService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.5.2
//
// Created by Quasar Development at 24/05/2016
//
//---------------------------------------------------



public interface PGEIServiceEvents
{
    public void Starting();
    public void Completed(PGEOperationResult result);
}
