package webService;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.5.2
//
// Created by Quasar Development at 24/05/2016
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class PGEOnlineIntegrationServiceSoapBinding
{
    interface PGEIWcfMethod
    {
        PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://localhost:8080/software-engeneering-wildfly-archetype-ejb/OnlineIntegration";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    PGEIServiceEvents callback;
    public PGEOnlineIntegrationServiceSoapBinding(){}

    public PGEOnlineIntegrationServiceSoapBinding (PGEIServiceEvents callback)
    {
        this.callback = callback;
    }
    public PGEOnlineIntegrationServiceSoapBinding(PGEIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public PGEOnlineIntegrationServiceSoapBinding(PGEIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected PGEExtendedSoapSerializationEnvelope createEnvelope()
    {
        PGEExtendedSoapSerializationEnvelope envelope= new PGEExtendedSoapSerializationEnvelope(PGEExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,PGEExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,PGEExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public PGEsessionResponse login(final String arg0,final String arg1 ) throws java.lang.Exception
    {
        return (PGEsessionResponse)execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "login");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PGEsessionResponse)getResult(PGEsessionResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< PGEsessionResponse>> loginAsync(final String arg0,final String arg1)
    {
        return executeAsync(new PGEFunctions.IFunc< PGEsessionResponse>() {
            public PGEsessionResponse Func() throws java.lang.Exception {
                return login( arg0,arg1);
            }
        });
    }
    
    public PGEmeetsResponse getMeetsByUser(final String arg0 ) throws java.lang.Exception
    {
        return (PGEmeetsResponse)execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeetsByUser");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PGEmeetsResponse)getResult(PGEmeetsResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< PGEmeetsResponse>> getMeetsByUserAsync(final String arg0)
    {
        return executeAsync(new PGEFunctions.IFunc< PGEmeetsResponse>() {
            public PGEmeetsResponse Func() throws java.lang.Exception {
                return getMeetsByUser( arg0);
            }
        });
    }
    
    public PGEmeetsResponse getMeetsByCategory(final String arg0,final String arg1 ) throws java.lang.Exception
    {
        return (PGEmeetsResponse)execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeetsByCategory");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg1!=null?arg1:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PGEmeetsResponse)getResult(PGEmeetsResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< PGEmeetsResponse>> getMeetsByCategoryAsync(final String arg0,final String arg1)
    {
        return executeAsync(new PGEFunctions.IFunc< PGEmeetsResponse>() {
            public PGEmeetsResponse Func() throws java.lang.Exception {
                return getMeetsByCategory( arg0,arg1);
            }
        });
    }
    
    public void init( ) throws java.lang.Exception
    {
        execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "init");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return null;
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< Void>> initAsync()
    {
        return executeAsync(new PGEFunctions.IFunc< Void>()
        {
            @Override
            public Void Func() throws java.lang.Exception {
                init( );
                return null;
            }
        }) ;
    }
    
    public PGEmeetResponse getMeet(final String arg0,final Integer arg1 ) throws java.lang.Exception
    {
        return (PGEmeetResponse)execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "getMeet");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PGEmeetResponse)getResult(PGEmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< PGEmeetResponse>> getMeetAsync(final String arg0,final Integer arg1)
    {
        return executeAsync(new PGEFunctions.IFunc< PGEmeetResponse>() {
            public PGEmeetResponse Func() throws java.lang.Exception {
                return getMeet( arg0,arg1);
            }
        });
    }
    
    public PGEmeetResponse leaveMeet(final String arg0,final Integer arg1 ) throws java.lang.Exception
    {
        return (PGEmeetResponse)execute(new PGEIWcfMethod()
        {
            @Override
            public PGEExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              PGEExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://web/", "leaveMeet");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg0";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(arg0!=null?arg0:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="";
                __info.name="arg1";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(arg1);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(PGEExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (PGEmeetResponse)getResult(PGEmeetResponse.class,__result,"return",__envelope);
            }
        },"");
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< PGEmeetResponse>> leaveMeetAsync(final String arg0,final Integer arg1)
    {
        return executeAsync(new PGEFunctions.IFunc< PGEmeetResponse>() {
            public PGEmeetResponse Func() throws java.lang.Exception {
                return leaveMeet( arg0,arg1);
            }
        });
    }
    
    public String register(final String arg0,final String arg1,final String arg2 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> registerAsync(final String arg0,final String arg1,final String arg2)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return register( arg0,arg1,arg2);
            }
        });
    }
    
    public String joinMeet(final String arg0,final String arg1 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> joinMeetAsync(final String arg0,final String arg1)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return joinMeet( arg0,arg1);
            }
        });
    }
    
    public String getMeets(final String arg0,final String arg1,final String arg2 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> getMeetsAsync(final String arg0,final String arg1,final String arg2)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getMeets( arg0,arg1,arg2);
            }
        });
    }
    
    public String createMeet(final String arg0,final String arg1,final String arg2,final String arg3,final String arg4,final String arg5,final String arg6 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> createMeetAsync(final String arg0,final String arg1,final String arg2,final String arg3,final String arg4,final String arg5,final String arg6)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return createMeet( arg0,arg1,arg2,arg3,arg4,arg5,arg6);
            }
        });
    }
    
    public String getCategories(final String arg0 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> getCategoriesAsync(final String arg0)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return getCategories( arg0);
            }
        });
    }
    
    public String logout(final String arg0 ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, PGEOperationResult< String>> logoutAsync(final String arg0)
    {
        return executeAsync(new PGEFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return logout( arg0);
            }
        });
    }

    
    protected java.lang.Object execute(PGEIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        PGEExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, PGEOperationResult< T>>  executeAsync(final PGEFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, PGEOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected PGEOperationResult< T> doInBackground(Void... params) {
                PGEOperationResult< T> result = new PGEOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(PGEOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,PGEExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


