package webService;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.5.5.2
//
// Created by Quasar Development at 24/05/2016
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class PGEuser extends AttributeContainer implements KvmSerializable
{

    
    public String description;
    
    public ArrayList< PGEmeet> meetsCreated =new ArrayList<PGEmeet >();
    
    public String password;
    
    public String userName;

    public PGEuser ()
    {
    }

    public PGEuser (java.lang.Object paramObj,PGEExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("description"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.description = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.description = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("meetsCreated"))
                {
                    if(obj!=null)
                    {
        
                    
                        if(this.meetsCreated==null)
                        {
                            this.meetsCreated = new ArrayList<PGEmeet>();
                        }
                        java.lang.Object j =obj;
                        PGEmeet j1= (PGEmeet)__envelope.get(j,PGEmeet.class);
                        this.meetsCreated.add(j1);
                   
        
                    }
                    continue;
                }
                if (info.name.equals("password"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.password = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.password = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("userName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.userName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.userName = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.description!=null?this.description:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.password!=null?this.password:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.userName!=null?this.userName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=+3 && propertyIndex< + 3+this.meetsCreated.size())
        {
            return this.meetsCreated.get(propertyIndex-(+3));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3+meetsCreated.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "description";
            info.namespace= "";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "password";
            info.namespace= "";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "userName";
            info.namespace= "";
        }
        if(propertyIndex>=+3 && propertyIndex <= +3+this.meetsCreated.size())
        {
            info.type = PGEmeet.class;
            info.name = "meetsCreated";
            info.namespace= "";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
